export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

/* REQUEST ROBOTS */
export const REQUEST_ROBOTS_PENDING = 'REQUEST_ROBOTS_PENDING';
export const REQUEST_ROBOTS_SUCCESS = 'REQUEST_ROBOTS_SUCCESS';
export const REQUEST_ROBOTS_FAILURE = 'REQUEST_ROBOTS_FAILURE';
